meta_product_name: "focus."
meta_title: "focus. | manage your day"
meta_description: "A fun & simple way to customise your daily tasks."
meta_image: "cover.png" # should exist in `app/assets/images/`
